name: conda-fpp-analysis
dependencies:
  - python>=3.8,<3.11
  - numpy>=1.18,<2.0
  - scipy>=1.8.0,<2.0.0
  - tqdm>=4.62.3,<5.0.0
  - PyWavelets>=1.2.0,<2.0.0
  - numba>=0.55.1,<0.56.0
  - conda-forge::cupy>=9.0.0,<10.0.0
  - rapidsai::cusignal>=0.19,<=0.22
