name: default
channels:
- conda-forge
- rapidsai
- nvidia
dependencies:
- python >=3.9,<4
- cupy >=10,<11
- cudatoolkit >=11.8.0,<12
- pip
- pip:
  - numpy>=1.26.4, <3.0.0
  - scipy>=1.14.1, <2
  - tqdm>=4.66.5, <5
  - pywavelets>=1.7.0, <2
  - matplotlib>=3.9.2, <4
  - mpmath>=1.3.0, <2
