[tool.poetry]
name = "analysistools"
version = "0.1.0"
description = "Analysis tools for time series"
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
numpy = "^1.22.2"
scipy = "^1.8.0"
tqdm = "^4.62.3"
PyWavelets = "^1.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
