[tool.poetry]
name = "fppanalysis"
version = "0.1.1"
description = "Analysis tools for time series"
homepage = "https://github.com/uit-cosmo/fpp-analysis-tools"
authors = ["gregordecristoforo <gregor.decristoforo@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
numpy = "^1.18"
scipy = "^1.8.0"
tqdm = "^4.62.3"
PyWavelets = "^1.2.0"

cupy = { version = "^10.2", optional = true }
cusignal = { version = "^0.19", optional = true }

[tool.poetry.extras]
cupy = ["cupy"]
cusignal = ["cusignal"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
